# Generated by Django 2.1.5 on 2019-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=100)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('deviceID', models.TextField(default='abc123abc')),
                ('ical', models.TextField()),
            ],
        ),
    ]
