# Generated by Django 2.1.5 on 2019-01-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(default='', max_length=256)),
                ('done', models.BooleanField()),
                ('deadline', models.DateField()),
                ('tasks', models.ManyToManyField(to='task.Task')),
            ],
        ),
    ]
