# Generated by Django 2.1.5 on 2019-01-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20190127_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='deadline',
        ),
    ]
